### ISSUE TITLE
Update Name

### ISSUE THREAD

**Issue by valentinetom** [atmgc/dope-frontend#5]
See specifications [here](https://www.figma.com/file/ZzI0TudsWd5n1D8iG0mHff/DOPE?type=design&node-id=112-4333&mode=design&t=s6pYIWfeOoC3Vmyy-4)

**Comment by Auwalms** [comment]
@valentinetom This is part of the extension task and should be assigned to @chidubemthedev since he is working on that. The whole issue should be moved to the extension repo if possible
